[package]
name = "nimble"
version = "0.1.0"
authors = ["Rasmus Michelsen <RMichelsen46@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.9", features = ["combaseapi", "d2d1", "dwrite", "errhandlingapi", "shobjidl", "winbase", "winuser", "windowsx"] }
ropey = "1.2.0"
